config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root  'static_pages#home'

  #Sign up/Sign inを促すページへのルーティング
  get '/static_pages/demand_sign_in' => 'static_pages#demand_sign_in'

  #ransack用ルーティング
  get '/spots/search' => 'spots#search'

  resources :prefectures, only: [:index, :show]
  resources :spots, except: [:destroy]
  resources :reviews
end

app/models/spot.rb
class Spot < ActiveRecord::Base
  has_many :reviews
  belongs_to :prefecture
end

app/controllers/spots_controller.rb
class SpotsController < LayoutsController
  def index
    @spots = Spot.all
    @prefectures = Prefecture.all
  end

  def show
    @spot = Spot.find(params[:id])
    @reviews = Review.where(spot_id: params[:id])
    @average = @reviews.average(:rate)
    @rate = ((@average / 5) * 100).round
  end

  def search
    @q = Spot.ransack(search_params)
    @results = @q.result
  end

  def new
    
  end

  def create
    
  end


    private

    def create_params
      
    end

    def search_params
      params.require(:q).permit(
        :name_cont,
        :prefecture_cont
        )
    end
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/search.html.erb
<p>hello</p>

<%= @results.each do |result| %>
  <%= result.name %>
<% end %>

app/views/spots/show.html.erb
<div class="content-block" id="blog">
  <div class="container blog-sec">
    <header class="block-heading cleafix">
      <a href="/reviews" class="btn btn-o btn-lg pull-right">View All</a>
      <div class="title-page">
        <p class="main-header"><%= @spot.name %></p>
        <% if @spot.reviews.present? %>
          <p class="sub-header">
            レビュー平均点：<%= @average %>点&nbsp;&nbsp;
            <div class="star-rating">
              <div class="star-rating-front" style="width: <%= @rate %>%">★★★★★</div>
              <div class="star-rating-back">★★★★★</div>
            </div>
          </p>
        <% else %>
          <p class="sub-header">レビュー平均点：まだレビューは投稿されていません</p>
        <% end %>
      </div>
    </header>
    <section class="block-body">
      <div class="row">
        <% @reviews.first(3).each do |review| %>
          <div class="col-sm-4 blog-post">
            <h2><%= review.user.id %></h2>
            <div class="star-rating-sm">
              <div class="star-rating-front" style="width: <%= ((review.rate.to_f/5)*100).to_i %>%">★★★★★</div>
              <div class="star-rating-back">★★★★★</div>
            </div>
            <p><%= review.comment.truncate(30, omission: '...') %></p>
            <a href="reviews/<%= review.id %>">Read More</a>
          </div>
        <% end %>
      </div>
    </section>
  </div>
</div><!-- #blog -->


<div class="content-block parallax" id="parallax">
  <div class="container">
    <h3 class="call-action pull-left">「<%= @spot.name %>」に対する、あなたの評価を登録しませんか？</h3>
    <%= link_to '評価を登録', new_review_path(@spot), class: "pull-right btn btn-o-white btn-lg" %>
  </div>
</div><!-- #parallax -->