config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root  'static_pages#home'

  #Sign up/Sign inを促すページへのルーティング
  get '/static_pages/demand_sign_in' => 'static_pages#demand_sign_in'

  #ransack用ルーティング
  get '/spots/search' => 'spots#search'

  resources :prefectures, only: [:index, :show]
  resources :spots, except: [:destroy]
  resources :reviews
end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController
    layout 'photo_spot'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoSpot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<%= yield %>


<script src="assets/javascripts/jquery-2.1.3.min.js"></script>
<script src="assets/javascripts/bootstrap.js"></script>
<script src="assets/javascripts/jquery.actual.min.js"></script>
<script src="assets/javascripts/jquery.scrollTo.min.js"></script>
<script src="assets/javascripts/contact.js"></script>
<script src="assets/javascripts/script.js"></script>
<script src="assets/javascripts/smoothscroll.js"></script>
<script type="text/javascript">
jQuery(document).ready(function($){

    $(window).scroll(function() {
      
      console.log("asdf");

    if ($(window).scrollTop() > 100 ){
    
    $('.top-header').addClass('shows');
    
      } else {
    
      $('.top-header').removeClass('shows');
    
    };    
  });

  });

jQuery('.scroll').on('click', function(e){    
    e.preventDefault()
    
  jQuery('html, body').animate({
      scrollTop : jQuery(this.hash).offset().top
    }, 1500);
});


</script>

</html>

app/views/layouts/photo_spot.html.erb
<!DOCTYPE html>
<head>
  <title>PhotoSpot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header class="top-header">
      <div class="container">
        <div class="row">
          <div class="col-md-3 col-xs-5 col-sm-4 header-logo">
            <br>
            <%= link_to root_path do %>
              <h1 class="logo">Photo<span class="logo-head">Spots</span></h1>
            <% end %>
          </div>

          <div class="col-md-8 col-md-offset-1 col-xs-7">
            <nav class="navbar navbar-default">
                <div class="container-fluid nav-bar">
                <!-- Brand and toggle get grouped for better mobile display -->
                  <div class="navbar-header">
                      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                      </button>
                  </div>

                  <!-- Collect the nav links, forms, and other content for toggling -->
                  <% if user_signed_in? %>
                    <div class="collapse navbar-collapse navbar-def" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                          <li>
                            <%= link_to root_path do %>
                              <i class="fa fa-home"></i> Home
                            <% end %>
                          </li>
                          <li>
                            <%= link_to spots_path, method: :get do %>
                              <i class="fa fa-map-pin"></i> 撮影スポット
                            <% end %>
                          </li>
                          <li>
                            <%= link_to destroy_user_session_path, method: :delete do %>
                              <i class="fa fa-sign-out"></i> ログアウト
                            <% end %>
                          </li>
                        </ul>
                    </div><!-- /navbar-collapse -->
                  <% else %>
                    <div class="collapse navbar-collapse navbar-def" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                          <li>
                            <%= link_to root_path do %>
                              <i class="fa fa-home"></i> Home
                            <% end %>
                          </li>
                          <li>
                            <%= link_to prefectures_path, method: :get  do %>
                              <i class="fa fa-map-pin"></i> 撮影スポット
                            <% end %>
                          </li>
                          <li>
                            <%= link_to new_user_session_path, method: :get do %>
                              <i class="fa fa-sign-in"></i> ログイン
                            <% end %>
                          </li>
                          <li>
                            <%= link_to new_user_registration_path, method: :get do %>
                              <i class="fa fa-user-plus"></i> 新規登録
                            <% end %>
                          </li>
                        </ul>
                    </div><!-- /navbar-collapse -->
                  <% end %>
                </div><!-- / .container-fluid -->
            </nav>
          </div>
        </div>
      </div>
    </header>

<%= yield %>

</body>

<script src="assets/js/jquery-2.1.3.min.js"></script>
<script src="assets/js/bootstrap.js"></script>
<script src="assets/js/jquery.actual.min.js"></script>
<script src="assets/js/jquery.scrollTo.min.js"></script>
<script src="assets/js/contact.js"></script>
<script src="assets/js/script.js"></script>
<script src="assets/js/smoothscroll.js"></script>
<script type="text/javascript">
jQuery(document).ready(function($){

    $(window).scroll(function() {
      
      console.log("asdf");

    if ($(window).scrollTop() > 100 ){
    
    $('.top-header').addClass('shows');
    
      } else {
    
      $('.top-header').removeClass('shows');
    
    };    
  });

  });

jQuery('.scroll').on('click', function(e){    
    e.preventDefault()
    
  jQuery('html, body').animate({
      scrollTop : jQuery(this.hash).offset().top
    }, 1500);
});


</script>